### PR TITLE
[COMMAND] Race

### PR DESCRIPTION
**Pull request by Lightninbolt986**
It uses some emotes to make the command look good. You can steal the emotes with the URL given or just remove that feature, up to you. 
Discord - lightninbolt986#3111

### CODE REVIEW

**Comment by Dauntless7** [comment]
I'll steal the emotes, no problem. Will test it soon and merge the PR once everything works well

**Comment by BrianWasTaken** [comment]
Just a little note: **don't use var** I mean, it's 2021 and some major sites don't recommend the keyword anymore.

**Comment by Hauntmore** [comment]
my OCD requires fixing pls. u should destruct classes from Discord.js (i suck)

**Comment by BrianWasTaken** [comment]
Looks great so uh @Dauntless7???

**Comment by Dauntless7** [comment]
> Looks great so uh @Dauntless7???

There's some weird permission issues in DMC atm with slash commands/bots that use slash commands so I'm waiting a bit till we sort that out

**Comment by BrianWasTaken** [comment]
> > Looks great so uh @Dauntless7???
> 
> There's some weird permission issues in DMC atm with slash commands/bots that use slash commands so I'm waiting a bit till we sort that out

hmmm Alright

**Comment by Dauntless7** [comment]
@Lightninbolt986 this is broken btw, and I can't contact you on Discord/find your old DM with me, I haven't had time to fix it yet.

**Comment by Lightninbolt986** [comment]
> @Lightninbolt986 this is broken btw, and I can't contact you on Discord/find your old DM with me, I haven't had time to fix it yet.

What exactly is broken? I tried DMing you on discord but I guess your DMs are off.

**Comment by Dauntless7** [comment]
> > @Lightninbolt986 this is broken btw, and I can't contact you on Discord/find your old DM with me, I haven't had time to fix it yet.
> 
> What exactly is broken? I tried DMing you on discord but I guess your DMs are off.

DMs are closed and I'm not reading all current DMs at all. Anyway, try booting the current version (I'm about to push an update to slash cmds + slash cmd permission setup) and you'll see the REST error that Discord gives, I believe the options just need fixing.

**Comment by Lightninbolt986** [comment]
> > > @Lightninbolt986 this is broken btw, and I can't contact you on Discord/find your old DM with me, I haven't had time to fix it yet.
> > 
> > 
> > What exactly is broken? I tried DMing you on discord but I guess your DMs are off.
> 
> DMs are closed and I'm not reading all current DMs. Anyway, try booting the current version (I'm about to push an update to slash cmds + slash cmd permission setup) and you'll see the REST error that Discord gives, I believe the options just need fixing.

Did not receive any error from REST just a basic TypeError, fixed that.

**Comment by Dauntless7** [comment]
Thanks, I'll have time to test it in around a week, as I have other changes to make until then.

**Pull request merged**
